services:
  webhook-hub:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: webhook-hub
    environment:
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - DB_PATH=/data/webhook.db
      - PORT=80
    volumes:
      - ./data:/data
    restart: always

  cloudflared:
    image: cloudflare/cloudflared
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    command: tunnel --no-autoupdate run
